

const monsterNameAutoComplete = [
    { label: 'Great Jagras' },
    { label: 'Kulu-Ya-Ku' },
    { label: 'Pukei-Pukei' },
    { label: 'Barroth' },
    { label: 'Jyuratodus' },
    { label: 'Tobi-Kadachi' },
    { label: 'Anjanath' },
    { label: 'Azure Rathalos' },
    { label: 'Bazelgeuse' },
    { label: 'Behemoth' },
    { label: 'Deviljho' },
    { label: 'Diablos' },
    { label: 'Black Diablos' },
    { label: 'Dodogama' },
    { label: 'Great Girros' },
    { label: 'Kirin' },
    { label: 'Kulve Taroth' },
    { label: 'Kushala Daora' },
    { label: 'Lavasioth' },
    { label: 'Legiana' },
    { label: 'Lunastra' },
    { label: 'Nergigante' },
    { label: 'Odogaron' },
    { label: 'Paolumu' },
    { label: 'Radobaan' },
    { label: 'Rathalos' },
    { label: 'Rathian' },
    { label: 'Pink Rathian' },
    { label: 'Teostra' },
    { label: 'Tzitzi-Ya-Ku' },
    { label: 'Uragaan' },
    { label: 'Vaal Hazak' },
    { label: "Xeno'jiiva" },
    { label: 'Zorah Magdaros' },
    { label: 'Leshen' },
    { label: 'Ancient Leshen' },
    { label: "Safi'jiiva" },
    { label: 'Stygian Zinogre' },
    { label: 'Rajang' },
    { label: 'Viper Tobi-Kadachi' },
    { label: 'Namielle' },
    { label: 'Zinogre' },
]

export default monsterNameAutoComplete