
const monsterNameAutoComplete = [
    'Anjanath',
    'Ancient Leshen',
    'Azure Rathalos',
    'Barroth',
    'Bazelgeuse',
    'Behemoth',
    'Black Diablos',
    'Deviljho',
    'Diablos',
    'Dodogama',
    'Great Girros',
    'Great Jagras',
    'Jyuratodus',
    'Kirin',
    'Kulve Taroth',
    'Kushala Daora',
    'Kulu-Ya-Ku',
    'Lavasioth',
    'Legiana',
    'Leshen',
    'Lunastra',
    'Namielle',
    'Nergigante',
    'Odogaron',
    'Paolumu',
    'Pink Rathian',
    'Pukei-Pukei',
    'Radobaan',
    'Rajang',
    'Rathalos',
    'Rathian',
    'Safi\'jiiva',
    'Stygian Zinogre',
    'Teostra',
    'Tobi-Kadachi',
    'Tzitzi-Ya-Ku',
    'Uragaan',
    'Vaal Hazak',
    'Viper Tobi-Kadachi',
    'Zinogre',
    'Zorah Magdaros',
    'Xeno\'jiiva'
];



// const monsterNameAutoComplete = [
//     { label: 'Anjanath' },
//     { label: 'Ancient Leshen' },
//     { label: 'Azure Rathalos' },
//     { label: 'Barroth' },
//     { label: 'Bazelgeuse' },
//     { label: 'Behemoth' },
//     { label: 'Black Diablos' },
//     { label: 'Deviljho' },
//     { label: 'Diablos' },
//     { label: 'Dodogama' },
//     { label: 'Great Girros' },
//     { label: 'Great Jagras' },
//     { label: 'Jyuratodus' },
//     { label: 'Kirin' },
//     { label: 'Kulve Taroth' },
//     { label: 'Kushala Daora' },
//     { label: 'Kulu-Ya-Ku' },
//     { label: 'Lavasioth' },
//     { label: 'Legiana' },
//     { label: 'Leshen' },
//     { label: 'Lunastra' },
//     { label: 'Namielle' },
//     { label: 'Nergigante' },
//     { label: 'Odogaron' },
//     { label: 'Paolumu' },
//     { label: 'Pink Rathian' },
//     { label: 'Pukei-Pukei' },
//     { label: 'Radobaan' },
//     { label: 'Rajang' },
//     { label: 'Rathalos' },
//     { label: 'Rathian' },
//     { label: 'Safi\'jiiva' },
//     { label: 'Stygian Zinogre' },
//     { label: 'Teostra' },
//     { label: 'Tobi-Kadachi' },
//     { label: 'Tzitzi-Ya-Ku' },
//     { label: 'Uragaan' },
//     { label: 'Vaal Hazak' },
//     { label: 'Viper Tobi-Kadachi' },
//     { label: 'Zinogre' },
//     { label: 'Zorah Magdaros' },
//     { label: 'Xeno\'jiiva' },
// ]

export default monsterNameAutoComplete