version: "3.8"
services:
  postgres-db:
    container_name: monster_hunter_database
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: monster_hunter_API
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5450:5432"

volumes:
  postgresql_data:
    driver: local