services:
  postgres-db:
    container_name: monster_killer
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: monster_killer
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5435:5432"

volumes:
  postgresql_data:
    driver: local
