INSERT INTO monster (id, name, icon, weakness_chart)
VALUES (18, 'Kulu-Ya-Ku', pg_read_binary_file('../MHAssets/icon/MHW_Kulu-Ya-Ku_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Kulu-Ya-Ku.png')),
       (19, 'Pukei-Pukei', pg_read_binary_file('../MHAssets/icon/MHW_Pukei-Pukei_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Pukei-Pukei.png')),
       (20, 'Barroth', pg_read_binary_file('../MHAssets/icon/MHW_Barroth_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Barroth.png')),
       (21, 'Jyuratodus', pg_read_binary_file('../MHAssets/icon/MHW_Jyuratodus_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Jyuratodus.png')),
       (22, 'Tobi-Kadachi', pg_read_binary_file('../MHAssets/icon/MHW_Tobi-Kadachi_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Tobi-Kadachi.png')),
       (23, 'Anjanath', pg_read_binary_file('../MHAssets/icon/MHW_Anjanath_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Anjanath.png')),
       (24, 'Azure Rathalos', pg_read_binary_file('../MHAssets/icon/MHW_Azure_Rathalos_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Azure Rathalos.png')),
       (25, 'Bazelgeuse', pg_read_binary_file('../MHAssets/icon/MHW_Bazelgeuse_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Bazelgeuse.png')),
       (26, 'Behemoth', pg_read_binary_file('../MHAssets/icon/MHW_Behemoth_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Behemoth.png')),
       (27, 'Deviljho', pg_read_binary_file('../MHAssets/icon/MHW_Deviljho_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Deviljho.png')),
       (28, 'Diablos', pg_read_binary_file('../MHAssets/icon/MHW_Diablos_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Diablos.png')),
       (29, 'Black Diablos', pg_read_binary_file('../MHAssets/icon/MHW_Black_Diablos_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Black Diablos.png')),
       (30, 'Dodogama', pg_read_binary_file('../MHAssets/icon/MHW_Dodogama_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Dodogama.png')),
       (31, 'Great Girros', pg_read_binary_file('../MHAssets/icon/MHW_Great_Girros_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Great Girros.png')),
       (32, 'Kirin', pg_read_binary_file('../MHAssets/icon/MHW_Kirin_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Kirin.png')),
       (33, 'Kulve Taroth', pg_read_binary_file('../MHAssets/icon/MHW_Kulve_Taroth_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Kulve Taroth.png')),
       (34, 'Kushala Daora', pg_read_binary_file('../MHAssets/icon/MHW_Kushala_Daora_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Kushala Daora.png')),
       (35, 'Lavasioth', pg_read_binary_file('../MHAssets/icon/MHW_Lavasioth_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Lavasioth.png')),
       (36, 'Legiana', pg_read_binary_file('../MHAssets/icon/MHW_Legiana_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Legiana.png')),
       (37, 'Lunastra', pg_read_binary_file('../MHAssets/icon/MHW_Lunastra_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Lunastra.png')),
       (38, 'Nergigante', pg_read_binary_file('../MHAssets/icon/MHW_Nergigante_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Nergigante.png')),
       (39, 'Odogaron', pg_read_binary_file('../MHAssets/icon/MHW_Odogaron_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Odogaron.png')),
       (40, 'Paolumu', pg_read_binary_file('../MHAssets/icon/MHW_Paolumu_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Paolumu.png')),
       (41, 'Radobaan', pg_read_binary_file('../MHAssets/icon/MHW_Radobaan_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Radobaan.png')),
       (42, 'Rathalos', pg_read_binary_file('../MHAssets/icon/MHW_Rathalos_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Rathalos.png')),
       (43, 'Rathian', pg_read_binary_file('../MHAssets/icon/MHW_Rathian_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Rathian.png')),
       (44, 'Pink Rathian', pg_read_binary_file('../MHAssets/icon/MHW_Pink_Rathian_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Pink Rathian.png')),
       (45, 'Teostra', pg_read_binary_file('../MHAssets/icon/MHW_Teostra_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Teostra.png')),
       (48, 'Tzitzi-Ya-Ku', pg_read_binary_file('../MHAssets/icon/MHW_Tzitzi-Ya-Ku_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Tzitzi-Ya-Ku.png')),
       (49, 'Uragaan', pg_read_binary_file('../MHAssets/icon/MHW_Uragaan_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Uragaan.png')),
       (50, 'Vaal Hazak', pg_read_binary_file('../MHAssets/icon/MHW_Vaal_Hazak_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Vaal Hazak.png')),
       (52, 'Zorah Magdaros', pg_read_binary_file('../MHAssets/icon/MHW_Zorah_Magdaros_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Zorah Magdaros.png')),
       (53, 'Leshen', pg_read_binary_file('../MHAssets/icon/MHW_Leshen_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Leshen.png')),
       (54, 'Ancient Leshen', pg_read_binary_file('../MHAssets/icon/MHW_Ancient_Leshen_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Ancient Leshen.png')),
       (56, 'Stygian Zinogre', pg_read_binary_file('../MHAssets/icon/MHW_Stygian_Zinogre_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Stygian Zinogre.png')),
       (57, 'Rajang', pg_read_binary_file('../MHAssets/icon/MHW_Rajang_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Rajang.png')),
       (58, 'Viper Tobi-Kadachi', pg_read_binary_file('../MHAssets/icon/MHW_Viper_Tobi-Kadachi_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Viper Tobi-Kadachi.png')),
       (59, 'Namielle', pg_read_binary_file('../MHAssets/icon/MHW_Namielle_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Namielle.png')),
       (60, 'Zinogre', pg_read_binary_file('../MHAssets/icon/MHW_Zinogre_Icon.webp'),
        pg_read_binary_file('../MHAssets/weakness_chart/Zinogre.png'));



--        (51, 'Xeno''jiiva', pg_read_binary_file('../MHAssets/icon/MHW_Xeno''jiiva_icon.webp'), 'none'),
--        (55, 'Safi''jiiva', pg_read_binary_file('../MHAssets/icon/MHW_Safi''jiiva_icon.webp'), 'none'),

