INSERT INTO monster_table (id, name, is_favorite) VALUES
                                                 (17, 'Great Jagras', false),
                                                 (18, 'Kulu-Ya-Ku', false),
                                                 (19, 'Pukei-Pukei', false),
                                                 (20, 'Barroth', false),
                                                 (21, 'Jyuratodus', false),
                                                 (22, 'Tobi-Kadachi', false),
                                                 (23, 'Anjanath', false),
                                                 (24, 'Azure Rathalos', false),
                                                 (25, 'Bazelgeuse', false),
                                                 (26, 'Behemoth', false),
                                                 (27, 'Deviljho', false),
                                                 (28, 'Diablos', false),
                                                 (29, 'Black Diablos', false),
                                                 (30, 'Dodogama', false),
                                                 (31, 'Great Girros', false),
                                                 (32, 'Kirin', false),
                                                 (33, 'Kulve Taroth', false),
                                                 (34, 'Kushala Daora', false),
                                                 (35, 'Lavasioth', false),
                                                 (36, 'Legiana', false),
                                                 (37, 'Lunastra', false),
                                                 (38, 'Nergigante', false),
                                                 (39, 'Odogaron', false),
                                                 (40, 'Paolumu', false),
                                                 (41, 'Radobaan', false),
                                                 (42, 'Rathalos', false),
                                                 (43, 'Rathian', false),
                                                 (44, 'Pink Rathian', false),
                                                 (45, 'Teostra', false),
                                                 (48, 'Tzitzi-Ya-Ku', false),
                                                 (49, 'Uragaan', false),
                                                 (50, 'Vaal Hazak', false),
                                                 (51, 'Xeno''jiiva', false),
(52, 'Zorah Magdaros', false),
(53, 'Leshen', false),
(54, 'Ancient Leshen', false),
(55, 'Safi''jiiva', false),
                                                 (56, 'Stygian Zinogre', false),
                                                 (57, 'Rajang', false),
                                                 (58, 'Viper Tobi-Kadachi', false),
                                                 (59, 'Namielle', false),
                                                 (60, 'Zinogre', false);
